// 肌肉群组定义
/**
 * 治疗程序适用的肌肉群组定义
 * 用于过滤哪些部位可以使用特定程序
 */

import {
    BACK_IMAGES,
    SHOULDER_IMAGES,
    ARM_IMAGES,
    FOREARM_IMAGES,
    TORSO_IMAGES,
    THIGH_IMAGES,
    CALF_IMAGES,
    ANKLE_IMAGES,
    GLUTE_IMAGES,
    NECK_IMAGES,
} from './images.js';

// 通用耐力训练组
export const GROUP_ENDURANCE = [
    BACK_IMAGES.SPINE,
    BACK_IMAGES.THORACIC_UPPER,
    BACK_IMAGES.LUMBAR,
    ARM_IMAGES.TRICEPS_LATERAL,
    SHOULDER_IMAGES.LATERAL_DELTOID,
    SHOULDER_IMAGES.TRAPEZIUS_UPPER,
    TORSO_IMAGES.PECTORALIS,
    TORSO_IMAGES.RECTUS_ABDOMINIS,
    TORSO_IMAGES.OBLIQUES,
    THIGH_IMAGES.RECTUS_FEMORIS,
    THIGH_IMAGES.VASTUS_LATERALIS,
    GLUTE_IMAGES.GLUTEUS_MEDIUS,
    GLUTE_IMAGES.GLUTEUS_MINIMUS,
    THIGH_IMAGES.HAMSTRINGS,
    CALF_IMAGES.SOLEUS_LATERAL,
    CALF_IMAGES.SOLEUS_MEDIAL,
    THIGH_IMAGES.VASTUS_INTERMEDIUS,
    CALF_IMAGES.GASTROCNEMIUS_MEDIAL,
    ARM_IMAGES.BICEPS_FRONT,
];

// 肥厚训练组
export const GROUP_HYPERTROPHY = [
    ARM_IMAGES.TRICEPS_LATERAL,
    TORSO_IMAGES.PECTORALIS,
    THIGH_IMAGES.RECTUS_FEMORIS,
    THIGH_IMAGES.VASTUS_LATERALIS,
    GLUTE_IMAGES.GLUTEUS_MEDIUS,
    GLUTE_IMAGES.GLUTEUS_MINIMUS,
    THIGH_IMAGES.HAMSTRINGS,
    CALF_IMAGES.SOLEUS_MEDIAL,
    ARM_IMAGES.BICEPS_FRONT,
];

// 拉伸训练组
export const GROUP_STRETCHING = [
    BACK_IMAGES.SPINE,
    BACK_IMAGES.THORACIC_UPPER,
    THIGH_IMAGES.RECTUS_FEMORIS,
    THIGH_IMAGES.HAMSTRINGS,
    CALF_IMAGES.SOLEUS_MEDIAL,
    ANKLE_IMAGES.ANKLE,
    THIGH_IMAGES.VASTUS_INTERMEDIUS,
    THIGH_IMAGES.SARTORIUS,
];

// 全面恢复组（适合多种恢复程序）
export const GROUP_RECOVERY = [
    SHOULDER_IMAGES.FRONT_DELTOID,
    SHOULDER_IMAGES.ANTERIOR_DELTOID,
    BACK_IMAGES.SPINE,
    BACK_IMAGES.THORACIC_UPPER,
    BACK_IMAGES.LUMBAR,
    ARM_IMAGES.TRICEPS_LATERAL,
    SHOULDER_IMAGES.LATERAL_DELTOID,
    SHOULDER_IMAGES.TRAPEZIUS_UPPER,
    TORSO_IMAGES.PECTORALIS,
    TORSO_IMAGES.RECTUS_ABDOMINIS,
    TORSO_IMAGES.OBLIQUES,
    FOREARM_IMAGES.PALMAR_FLEXORS,
    FOREARM_IMAGES.EXTENSORS,
    THIGH_IMAGES.RECTUS_FEMORIS,
    GLUTE_IMAGES.GLUTEUS_MEDIUS,
    GLUTE_IMAGES.GLUTEUS_MINIMUS,
    THIGH_IMAGES.HAMSTRINGS,
    CALF_IMAGES.SOLEUS_MEDIAL,
    CALF_IMAGES.GASTROCNEMIUS_LATERAL,
    ANKLE_IMAGES.ANKLE,
    THIGH_IMAGES.VASTUS_INTERMEDIUS,
    THIGH_IMAGES.SARTORIUS,
    THIGH_IMAGES.ADDUCTORS,
    BACK_IMAGES.THORACIC_LATERAL,
    THIGH_IMAGES.KNEE_FRONT,
    THIGH_IMAGES.VASTUS_MEDIALIS,
];

// 肌肉塑形组
export const GROUP_SHAPING = [
    ARM_IMAGES.TRICEPS_LATERAL,
    SHOULDER_IMAGES.LATERAL_DELTOID,
    TORSO_IMAGES.PECTORALIS,
    TORSO_IMAGES.RECTUS_ABDOMINIS,
    TORSO_IMAGES.OBLIQUES,
    THIGH_IMAGES.RECTUS_FEMORIS,
    GLUTE_IMAGES.GLUTEUS_MEDIUS,
    GLUTE_IMAGES.GLUTEUS_MINIMUS,
    CALF_IMAGES.SOLEUS_MEDIAL,
    ARM_IMAGES.BICEPS_FRONT,
    GLUTE_IMAGES.PIRIFORMIS,
];

// 血管循环组
export const GROUP_VASCULAR = [
    SHOULDER_IMAGES.FRONT_DELTOID,
    ARM_IMAGES.TRICEPS_LATERAL,
    SHOULDER_IMAGES.LATERAL_DELTOID,
    SHOULDER_IMAGES.TRAPEZIUS_UPPER,
    TORSO_IMAGES.PECTORALIS,
    THIGH_IMAGES.RECTUS_FEMORIS,
    THIGH_IMAGES.VASTUS_LATERALIS,
    GLUTE_IMAGES.GLUTEUS_MEDIUS,
    GLUTE_IMAGES.GLUTEUS_MINIMUS,
    THIGH_IMAGES.HAMSTRINGS,
    CALF_IMAGES.SOLEUS_MEDIAL,
    THIGH_IMAGES.VASTUS_INTERMEDIUS,
    THIGH_IMAGES.ADDUCTORS,
    BACK_IMAGES.THORACIC_LATERAL,
    ARM_IMAGES.BICEPS_FRONT,
];

// 淋巴引流组
export const GROUP_LYMPHATIC = [
    SHOULDER_IMAGES.FRONT_DELTOID,
    SHOULDER_IMAGES.ANTERIOR_DELTOID,
    ARM_IMAGES.TRICEPS_LATERAL,
    SHOULDER_IMAGES.TRAPEZIUS_UPPER,
    TORSO_IMAGES.RECTUS_ABDOMINIS,
    FOREARM_IMAGES.PALMAR_FLEXORS,
    FOREARM_IMAGES.EXTENSORS,
    FOREARM_IMAGES.ELBOW,
    THIGH_IMAGES.RECTUS_FEMORIS,
    GLUTE_IMAGES.GLUTEUS_MEDIUS,
    GLUTE_IMAGES.GLUTEUS_MINIMUS,
    THIGH_IMAGES.HAMSTRINGS,
    CALF_IMAGES.GASTROCNEMIUS_LATERAL,
    THIGH_IMAGES.VASTUS_INTERMEDIUS,
];

// 抽筋预防组
export const GROUP_CRAMP_PREVENTION = [
    THIGH_IMAGES.HAMSTRINGS,
    CALF_IMAGES.SOLEUS_LATERAL,
    CALF_IMAGES.SOLEUS_MEDIAL,
    CALF_IMAGES.GASTROCNEMIUS_LATERAL,
    CALF_IMAGES.GASTROCNEMIUS_MEDIAL,
    ANKLE_IMAGES.ANKLE,
    THIGH_IMAGES.VASTUS_INTERMEDIUS,
];

// 腿部沉重感组
export const GROUP_HEAVY_LEGS = [
    CALF_IMAGES.SOLEUS_LATERAL,
    CALF_IMAGES.SOLEUS_MEDIAL,
    ANKLE_IMAGES.ANKLE,
    THIGH_IMAGES.KNEE_FRONT,
];

// 疼痛治疗组
export const GROUP_PAIN_TREATMENT = [
    SHOULDER_IMAGES.FRONT_DELTOID,
    SHOULDER_IMAGES.ANTERIOR_DELTOID,
    NECK_IMAGES.CERVICAL_SIDE,
    SHOULDER_IMAGES.TRAPEZIUS_UPPER,
    FOREARM_IMAGES.ELBOW,
    ANKLE_IMAGES.ANKLE,
    NECK_IMAGES.CERVICAL_FRONT,
];

// 力量训练组
export const GROUP_STRENGTH = [
    SHOULDER_IMAGES.LATERAL_DELTOID,
    SHOULDER_IMAGES.TRAPEZIUS_UPPER,
    THIGH_IMAGES.RECTUS_FEMORIS,
    THIGH_IMAGES.VASTUS_LATERALIS,
    GLUTE_IMAGES.GLUTEUS_MINIMUS,
    THIGH_IMAGES.HAMSTRINGS,
    CALF_IMAGES.SOLEUS_MEDIAL,
    THIGH_IMAGES.ADDUCTORS,
    ARM_IMAGES.BICEPS_FRONT,
];
