// 图片ID常量定义
/**
 * 人体部位图片ID常量定义
 * 用于标识不同肌肉群组的图片资源
 */

// 颈部区域
export const NECK_IMAGES = {
    CERVICAL_FRONT: 11,
    CERVICAL_BACK: 14,
    CERVICAL_SIDE: 151,
};

// 背部区域
export const BACK_IMAGES = {
    SPINE: 22,
    SPINE_UPPER: 137,
    THORACIC_UPPER: 30,
    THORACIC_MID: 141,
    THORACIC_LOWER: 142,
    THORACIC_LATERAL: 144,
    LUMBAR: 32,
};

// 肩部区域
export const SHOULDER_IMAGES = {
    FRONT_DELTOID: 4,
    ANTERIOR_DELTOID: 20,
    LATERAL_DELTOID: 59,
    POSTERIOR_DELTOID: 64,
    TRAPEZIUS_UPPER: 67,
    TRAPEZIUS_MID: 71,
    TRAPEZIUS_LOWER: 72,
};

// 手臂区域
export const ARM_IMAGES = {
    BICEPS_FRONT: 146,
    BRACHIALIS: 147,
    TRICEPS_LATERAL: 36,
    TRICEPS_MEDIAL: 40,
};

// 前臂区域
export const FOREARM_IMAGES = {
    ELBOW: 93,
    PALMAR_FLEXORS: 87,
    EXTENSORS: 90,
};

// 躯干区域
export const TORSO_IMAGES = {
    PECTORALIS: 75,
    RECTUS_ABDOMINIS: 80,
    OBLIQUES: 83,
};

// 大腿区域
export const THIGH_IMAGES = {
    RECTUS_FEMORIS: 96,
    VASTUS_LATERALIS: 101,
    VASTUS_MEDIALIS: 158,
    VASTUS_INTERMEDIUS: 131,
    SARTORIUS: 135,
    ADDUCTORS: 133,
    KNEE_FRONT: 150,
    HAMSTRINGS: 111,
};

// 小腿区域
export const CALF_IMAGES = {
    GASTROCNEMIUS_LATERAL: 122,
    GASTROCNEMIUS_MEDIAL: 129,
    SOLEUS_LATERAL: 116,
    SOLEUS_MEDIAL: 120,
};

// 踝足区域
export const ANKLE_IMAGES = {
    ANKLE: 126,
};

// 臀部区域
export const GLUTE_IMAGES = {
    GLUTEUS_MAXIMUS: 104,
    GLUTEUS_MEDIUS: 106,
    GLUTEUS_MINIMUS: 107,
    PIRIFORMIS: 153,
};

// 所有正面图片
export const ALL_FRONTAL_IMAGES = [
    SHOULDER_IMAGES.FRONT_DELTOID,
    SHOULDER_IMAGES.ANTERIOR_DELTOID,
    SHOULDER_IMAGES.LATERAL_DELTOID,
    SHOULDER_IMAGES.POSTERIOR_DELTOID,
    ARM_IMAGES.BICEPS_FRONT,
    ARM_IMAGES.BRACHIALIS,
    FOREARM_IMAGES.PALMAR_FLEXORS,
    FOREARM_IMAGES.EXTENSORS,
    TORSO_IMAGES.PECTORALIS,
    THIGH_IMAGES.RECTUS_FEMORIS,
    THIGH_IMAGES.VASTUS_LATERALIS,
    THIGH_IMAGES.VASTUS_MEDIALIS,
    THIGH_IMAGES.VASTUS_INTERMEDIUS,
    THIGH_IMAGES.SARTORIUS,
    THIGH_IMAGES.ADDUCTORS,
    THIGH_IMAGES.KNEE_FRONT,
    CALF_IMAGES.GASTROCNEMIUS_LATERAL,
    CALF_IMAGES.GASTROCNEMIUS_MEDIAL,
    ANKLE_IMAGES.ANKLE,
    TORSO_IMAGES.RECTUS_ABDOMINIS,
    TORSO_IMAGES.OBLIQUES,
];

// 所有背面图片
export const ALL_POSTERIOR_IMAGES = [
    NECK_IMAGES.CERVICAL_FRONT,
    NECK_IMAGES.CERVICAL_BACK,
    NECK_IMAGES.CERVICAL_SIDE,
    BACK_IMAGES.SPINE,
    BACK_IMAGES.SPINE_UPPER,
    BACK_IMAGES.THORACIC_UPPER,
    BACK_IMAGES.THORACIC_MID,
    BACK_IMAGES.THORACIC_LOWER,
    BACK_IMAGES.THORACIC_LATERAL,
    BACK_IMAGES.LUMBAR,
    SHOULDER_IMAGES.TRAPEZIUS_UPPER,
    SHOULDER_IMAGES.TRAPEZIUS_MID,
    SHOULDER_IMAGES.TRAPEZIUS_LOWER,
    ARM_IMAGES.TRICEPS_LATERAL,
    ARM_IMAGES.TRICEPS_MEDIAL,
    FOREARM_IMAGES.ELBOW,
    THIGH_IMAGES.HAMSTRINGS,
    CALF_IMAGES.SOLEUS_LATERAL,
    CALF_IMAGES.SOLEUS_MEDIAL,
    GLUTE_IMAGES.GLUTEUS_MAXIMUS,
    GLUTE_IMAGES.GLUTEUS_MEDIUS,
    GLUTE_IMAGES.GLUTEUS_MINIMUS,
    GLUTE_IMAGES.PIRIFORMIS,
];
